import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";
import ClientContext from "./ClientContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClientContext>
      <html lang="en" className={inter.className}>
        <body>
          <div className="flex flex-col w-screen h-screen">
            <NavigationBar />
            {children}
          </div>
        </body>
      </html>
    </ClientContext>
  );
}
